version: "3.8"
services:
  app:
    build:
      # Build an image from the Dockerfile in the current directory
      context: .
    ports:
      - "8080:80"
    env_file:
      - twitter-stream-app.env
    environment:
      PORT: "80"
